# Generated by Django 4.2.10 on 2025-03-06 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('energy', '0084_alter_performainvoice_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('hour', models.IntegerField()),
                ('purchase_bid', models.FloatField()),
                ('total_sell_bid', models.FloatField()),
                ('sell_bid_solar', models.FloatField()),
                ('sell_bid_non_solar', models.FloatField()),
                ('sell_bid_hydro', models.FloatField()),
                ('mcv_total', models.FloatField()),
                ('mcv_solar', models.FloatField()),
                ('mcv_non_solar', models.FloatField()),
                ('mcv_hydro', models.FloatField()),
                ('mcp', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerMonthAheadDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('demand', models.FloatField()),
                ('price_details', models.JSONField()),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.consumerrequirements')),
            ],
        ),
        migrations.CreateModel(
            name='MonthAheadGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('generation', models.FloatField()),
                ('price', models.IntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'app_label': 'energy', 'model__in': ['solarportfolio', 'windportfolio']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='MonthAheadPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('hour', models.IntegerField()),
                ('mcv_prediction', models.FloatField(blank=True, null=True)),
                ('mcp_prediction', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NextDayPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('hour', models.IntegerField()),
                ('mcv_prediction', models.FloatField(blank=True, null=True)),
                ('mcp_prediction', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powerx_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthAheadGenerationDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('distributed_generation', models.FloatField()),
                ('month_ahead_generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_distributions', to='powerx.monthaheadgeneration')),
            ],
        ),
        migrations.CreateModel(
            name='DayAheadGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('generation', models.IntegerField()),
                ('price', models.IntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'app_label': 'energy', 'model__in': ['solarportfolio', 'windportfolio']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerMonthAheadDemandDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('distributed_demand', models.FloatField()),
                ('month_ahead_demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='powerx.consumermonthaheaddemand')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerDayAheadDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('demand', models.IntegerField()),
                ('price_details', models.JSONField(blank=True, null=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.consumerrequirements')),
            ],
        ),
    ]
