# Generated by Django 4.2.10 on 2025-02-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumertradingdemand',
            name='energy_type',
            field=models.CharField(choices=[('Solar', 'Solar'), ('Wind', 'Wind'), ('Hydro', 'Hydro')], max_length=50),
        ),
    ]
