# Generated by Django 4.2.10 on 2025-02-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerx', '0002_alter_consumertradingdemand_energy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumertradingdemand',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consumertradingdemand',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
