# Generated by Django 4.2.10 on 2025-02-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerx', '0004_consumertradingdemand_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('hour', models.IntegerField()),
                ('purchase_bid', models.FloatField()),
                ('total_sell_bid', models.FloatField()),
                ('sell_bid_solar', models.FloatField()),
                ('sell_bid_non_solar', models.FloatField()),
                ('sell_bid_hydro', models.FloatField()),
                ('mcv_total', models.FloatField()),
                ('mcv_non_solar', models.FloatField()),
                ('mcv_hydro', models.FloatField()),
                ('mcp', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NextDayprediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('hour', models.IntegerField()),
                ('mcv_prediction', models.FloatField()),
                ('mcp_prediction', models.FloatField()),
            ],
        ),
    ]
