# Generated by Django 4.2.10 on 2025-02-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerx', '0005_cleandata_nextdayprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleandata',
            name='mcv_solar',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
