# Generated by Django 4.2.10 on 2025-02-28 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('powerx', '0007_alter_nextdayprediction_mcp_prediction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthAheadPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('hour', models.IntegerField()),
                ('mcv_prediction', models.FloatField(blank=True, null=True)),
                ('mcp_prediction', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ConsumerTradingDemand',
            new_name='ConsumerDayAheadDemand',
        ),
    ]
