# Generated by Django 5.1.4 on 2024-12-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='cin_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='landmark',
            new_name='company_representative',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='other_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='web',
        ),
    ]
