# Generated by Django 5.1.4 on 2025-01-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_otp_user_email_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
