# Generated by Django 4.2.10 on 2025-01-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_mobile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='re_index',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
