# Generated by Django 4.2.10 on 2025-01-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_re_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_visited_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_paid',
            field=models.BooleanField(default=False),
        ),
    ]
