# Generated by Django 4.2.10 on 2025-01-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_last_visited_page_user_subscription_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_paid',
        ),
    ]
