# Generated by Django 4.2.10 on 2025-01-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_subscription_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Management', 'Management'), ('Edit Access', 'Edit Access'), ('View Only', 'View Only')], max_length=50, null=True),
        ),
    ]
