# Generated by Django 4.2.10 on 2025-01-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='solar_template_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='wind_template_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
