# Generated by Django 4.2.10 on 2025-02-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_solar_template_downloaded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='solar_template_downloaded',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='wind_template_downloaded',
            field=models.BooleanField(default=True),
        ),
    ]
