# Generated by Django 4.2.10 on 2025-02-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_solar_template_downloaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_requirement_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
