from django.contrib import admin
from .models import GeneratorHourlyDemand, GeneratorMonthlyConsumption, NationalHoliday, NegotiationInvitation, PeakHours, State, Industry, PaymentTransaction, SolarPortfolio, StateTimeSlot, SubIndustry, WindPortfolio, ESSPortfolio, ConsumerRequirements, MonthlyConsumptionData, HourlyDemand, Combination, StandardTermsSheet, MatchingIPP, SubscriptionType, SubscriptionEnrolled, Notifications, Tariffs,GeneratorOffer, NegotiationWindow, MasterTable, GridTariff, ScadaFile, RETariffMasterTable, PerformaInvoice

# Register your models here.
admin.site.register(SolarPortfolio)
admin.site.register(WindPortfolio)
admin.site.register(ESSPortfolio)
admin.site.register(ConsumerRequirements)
admin.site.register(MonthlyConsumptionData)
admin.site.register(HourlyDemand)
admin.site.register(Combination)
admin.site.register(StandardTermsSheet)
admin.site.register(MatchingIPP)
admin.site.register(SubscriptionType)
admin.site.register(SubscriptionEnrolled)
admin.site.register(Notifications)
admin.site.register(Tariffs)
admin.site.register(GeneratorOffer)
admin.site.register(NegotiationWindow)
admin.site.register(NegotiationInvitation)
admin.site.register(MasterTable)
admin.site.register(GridTariff)
admin.site.register(ScadaFile)
admin.site.register(PaymentTransaction)
admin.site.register(RETariffMasterTable)
admin.site.register(State)
admin.site.register(Industry)
admin.site.register(SubIndustry)
admin.site.register(PerformaInvoice)
admin.site.register(StateTimeSlot)
admin.site.register(GeneratorHourlyDemand)
admin.site.register(PeakHours)
admin.site.register(NationalHoliday)

@admin.register(GeneratorMonthlyConsumption)
class GeneratorMonthlyConsumptionAdmin(admin.ModelAdmin):
    list_display = ('generator', 'month', 'monthly_consumption', 'peak_consumption', 'off_peak_consumption', 'monthly_bill_amount')