# Generated by Django 5.1.4 on 2024-12-22 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('contracted_demand', models.IntegerField()),
                ('tariff_category', models.CharField(max_length=255)),
                ('voltage_level', models.CharField(max_length=255)),
                ('procurement_date', models.DateField()),
                ('user', models.ForeignKey(limit_choices_to={'user_category': 'Consumer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GenerationPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_type', models.CharField(choices=[('Solar', 'Solar'), ('Wind', 'Wind'), ('ESS', 'ESS')], max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('cod', models.DateField()),
                ('updated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(limit_choices_to={'user_category': 'Generator'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
