# Generated by Django 5.1.4 on 2024-12-22 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyConsumptionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=255)),
                ('monthly_consumption', models.IntegerField()),
                ('peak_consumption', models.IntegerField()),
                ('off_peak_consumption', models.IntegerField()),
                ('monthly_bill_amount', models.IntegerField()),
                ('user', models.ForeignKey(limit_choices_to={'user_category': 'Consumer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
