# Generated by Django 5.1.4 on 2024-12-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_monthlyconsumptiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationportfolio',
            name='annual_generation_potential',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationportfolio',
            name='capital_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationportfolio',
            name='efficiency_of_dispatch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationportfolio',
            name='efficiency_of_storage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationportfolio',
            name='hourly_data',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationportfolio',
            name='marginal_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationportfolio',
            name='total_install_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
