# Generated by Django 5.1.4 on 2024-12-13 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_tariffs_analytics_contracts_energydemands_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='energyprofiles',
            old_name='available_capacity',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='energyprofiles',
            name='maximum_capacity',
        ),
        migrations.RemoveField(
            model_name='energyprofiles',
            name='pricing',
        ),
        migrations.AddField(
            model_name='energyprofiles',
            name='cod',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energyprofiles',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='energyprofiles',
            name='unit',
            field=models.CharField(choices=[('kW', 'Kilowatt'), ('MW', 'Megawatt'), ('GW', 'Gigawatt')], default='kW', max_length=2),
        ),
        migrations.AlterField(
            model_name='energyprofiles',
            name='energy_type',
            field=models.CharField(choices=[('Solar', 'Solar'), ('Wind', 'Wind'), ('ESS', 'ESS')], max_length=255),
        ),
        migrations.AlterField(
            model_name='energyprofiles',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_category': 'Generator'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
