# Generated by Django 5.1.4 on 2024-12-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_generationportfolio_annual_generation_potential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationportfolio',
            name='year_of_commissioning',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
