# Generated by Django 5.1.4 on 2024-12-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0005_remove_generationportfolio_year_of_commissioning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerrequirements',
            name='voltage_level',
            field=models.IntegerField(),
        ),
    ]
