# Generated by Django 5.1.4 on 2024-12-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0006_alter_consumerrequirements_voltage_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationportfolio',
            name='connectivity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
