# Generated by Django 5.1.4 on 2024-12-30 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0007_generationportfolio_connectivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyconsumptiondata',
            name='bill',
            field=models.FileField(blank=True, null=True, upload_to='bills/'),
        ),
        migrations.CreateModel(
            name='ESSPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('connectivity', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.IntegerField()),
                ('total_install_capacity', models.IntegerField(blank=True, null=True)),
                ('capital_cost', models.IntegerField(blank=True, null=True)),
                ('marginal_cost', models.IntegerField(blank=True, null=True)),
                ('cod', models.DateField()),
                ('updated', models.BooleanField(default=False)),
                ('efficiency_of_storage', models.IntegerField(blank=True, null=True)),
                ('efficiency_of_dispatch', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(limit_choices_to={'user_category': 'Generator'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolarPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('connectivity', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.IntegerField()),
                ('total_install_capacity', models.IntegerField(blank=True, null=True)),
                ('capital_cost', models.IntegerField(blank=True, null=True)),
                ('marginal_cost', models.IntegerField(blank=True, null=True)),
                ('cod', models.DateField()),
                ('updated', models.BooleanField(default=False)),
                ('hourly_data', models.FileField(blank=True, null=True, upload_to='hourly_data/')),
                ('annual_generation_potential', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(limit_choices_to={'user_category': 'Generator'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WindPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('connectivity', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.IntegerField()),
                ('total_install_capacity', models.IntegerField(blank=True, null=True)),
                ('capital_cost', models.IntegerField(blank=True, null=True)),
                ('marginal_cost', models.IntegerField(blank=True, null=True)),
                ('cod', models.DateField()),
                ('updated', models.BooleanField(default=False)),
                ('hourly_data', models.FileField(blank=True, null=True, upload_to='hourly_data/')),
                ('annual_generation_potential', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(limit_choices_to={'user_category': 'Generator'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='GenerationPortfolio',
        ),
    ]
