# Generated by Django 5.1.4 on 2024-12-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0008_monthlyconsumptiondata_bill_essportfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerrequirements',
            name='contracted_demand',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='essportfolio',
            name='capacity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='essportfolio',
            name='capital_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='essportfolio',
            name='efficiency_of_dispatch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='essportfolio',
            name='efficiency_of_storage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='essportfolio',
            name='marginal_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='essportfolio',
            name='total_install_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyconsumptiondata',
            name='monthly_bill_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='monthlyconsumptiondata',
            name='monthly_consumption',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='monthlyconsumptiondata',
            name='off_peak_consumption',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='monthlyconsumptiondata',
            name='peak_consumption',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solarportfolio',
            name='annual_generation_potential',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarportfolio',
            name='capacity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solarportfolio',
            name='capital_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarportfolio',
            name='marginal_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarportfolio',
            name='total_install_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windportfolio',
            name='annual_generation_potential',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windportfolio',
            name='capacity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='windportfolio',
            name='capital_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windportfolio',
            name='marginal_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windportfolio',
            name='total_install_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
