# Generated by Django 5.1.4 on 2024-12-30 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0009_alter_consumerrequirements_contracted_demand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_demand', models.TextField()),
                ('bulk_file', models.FileField(blank=True, null=True, upload_to='bulk_file/')),
                ('user', models.OneToOneField(limit_choices_to={'user_category': 'Consumer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
