# Generated by Django 5.1.4 on 2024-12-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0010_hourlydemand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlydemand',
            name='hourly_demand',
            field=models.TextField(blank=True, null=True),
        ),
    ]
