# Generated by Django 5.1.4 on 2024-12-31 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0011_alter_hourlydemand_hourly_demand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardTermsSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_of_ppa', models.PositiveIntegerField(help_text='Term of PPA in years')),
                ('lock_in_period', models.PositiveIntegerField(help_text='Lock-in period in years')),
                ('commencement_of_supply', models.DateField(help_text='Commencement date of supply')),
                ('contracted_energy', models.FloatField(help_text='Contracted energy in million units')),
                ('minimum_supply_obligation', models.FloatField(help_text='Minimum supply obligation in million units')),
                ('payment_security_day', models.PositiveIntegerField(help_text='Payment security duration in days')),
                ('payment_security_type', models.CharField(blank=True, help_text='Type of payment security', max_length=100, null=True)),
                ('count', models.IntegerField(default=0, help_text='Used for counting iterations, only 4 iterations are valid')),
                ('consumer', models.ForeignKey(limit_choices_to={'user_category': 'Consumer'}, on_delete=django.db.models.deletion.CASCADE, related_name='consumer_terms_sheets', to=settings.AUTH_USER_MODEL)),
                ('generator', models.ForeignKey(limit_choices_to={'user_category': 'Generator'}, on_delete=django.db.models.deletion.CASCADE, related_name='generator_terms_sheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
