# Generated by Django 5.1.4 on 2025-01-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0012_standardtermssheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardtermssheet',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', help_text='Status of the terms sheet (Pending, Accepted, or Rejected)', max_length=100),
        ),
    ]
