# Generated by Django 5.1.4 on 2025-01-01 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0013_standardtermssheet_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlydemand',
            name='user',
        ),
        migrations.RemoveField(
            model_name='monthlyconsumptiondata',
            name='user',
        ),
        migrations.AddField(
            model_name='hourlydemand',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.consumerrequirements'),
        ),
        migrations.AddField(
            model_name='monthlyconsumptiondata',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.consumerrequirements'),
        ),
        migrations.AddField(
            model_name='standardtermssheet',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.consumerrequirements'),
        ),
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination', models.CharField(max_length=200)),
                ('request_sent', models.BooleanField(default=True)),
                ('consumer', models.ForeignKey(limit_choices_to={'user_category': 'Consumer'}, on_delete=django.db.models.deletion.CASCADE, related_name='consumer_combinations', to=settings.AUTH_USER_MODEL)),
                ('generator', models.ForeignKey(limit_choices_to={'user_category': 'Generator'}, on_delete=django.db.models.deletion.CASCADE, related_name='generator_combinations', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.consumerrequirements')),
            ],
        ),
    ]
