# Generated by Django 5.1.4 on 2025-01-01 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0014_remove_hourlydemand_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlydemand',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.consumerrequirements'),
        ),
        migrations.AlterField(
            model_name='monthlyconsumptiondata',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.consumerrequirements'),
        ),
    ]
