# Generated by Django 5.1.4 on 2025-01-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0015_alter_hourlydemand_requirement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combination',
            name='consumer',
        ),
        migrations.AddField(
            model_name='combination',
            name='annual_curtailment',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combination',
            name='annual_demand_offset',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combination',
            name='final_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combination',
            name='optimal_battery_capacity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combination',
            name='optimal_solar_capacity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combination',
            name='optimal_wind_capacity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combination',
            name='per_unit_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='combination',
            name='request_sent',
            field=models.BooleanField(default=False),
        ),
    ]
