# Generated by Django 5.1.4 on 2025-01-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0016_remove_combination_consumer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combination',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
