# Generated by Django 5.1.4 on 2025-01-02 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0018_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingIPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generator_ids', models.JSONField(default=list)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.consumerrequirements')),
            ],
        ),
    ]
