# Generated by Django 5.1.4 on 2025-01-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0020_subscriptiontype_subscriptionenrolled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionenrolled',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=50),
        ),
    ]
