# Generated by Django 5.1.4 on 2025-01-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0021_alter_subscriptionenrolled_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='user_type',
            field=models.CharField(choices=[('Consumer', 'Consumer'), ('Generator', 'Generator')], default='consumer', max_length=50),
        ),
    ]
