# Generated by Django 5.1.4 on 2025-01-06 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0025_tariffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffs',
            name='terms_sheet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='energy.standardtermssheet'),
            preserve_default=False,
        ),
    ]
