# Generated by Django 5.1.4 on 2025-01-06 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0026_tariffs_terms_sheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardtermssheet',
            name='generator',
        ),
        migrations.RemoveField(
            model_name='standardtermssheet',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='tariffs',
            name='combination',
        ),
        migrations.AddField(
            model_name='standardtermssheet',
            name='combination',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='energy.combination'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariffs',
            name='generator',
            field=models.ForeignKey(default=1, limit_choices_to={'user_category': 'Generator'}, on_delete=django.db.models.deletion.CASCADE, related_name='NewGenerator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
