# Generated by Django 5.1.4 on 2025-01-06 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0027_remove_standardtermssheet_generator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffs',
            name='generator',
        ),
        migrations.CreateModel(
            name='NegotiationOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_tariff', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generator', models.ForeignKey(limit_choices_to={'user_category': 'Generator'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('terms_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.standardtermssheet')),
            ],
        ),
    ]
