# Generated by Django 4.2.10 on 2025-01-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0029_rename_negotiationoffer_generatoroffer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essportfolio',
            old_name='capacity',
            new_name='available_capacity',
        ),
        migrations.RenameField(
            model_name='solarportfolio',
            old_name='capacity',
            new_name='available_capacity',
        ),
        migrations.RenameField(
            model_name='windportfolio',
            old_name='capacity',
            new_name='available_capacity',
        ),
        migrations.AlterField(
            model_name='generatoroffer',
            name='updated_tariff',
            field=models.FloatField(default=0),
        ),
    ]
