# Generated by Django 4.2.10 on 2025-01-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0030_rename_capacity_essportfolio_available_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
                ('tariff_category', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MatserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
                ('RE_tariff', models.IntegerField()),
                ('ISTS_charges', models.IntegerField()),
                ('state_charges', models.IntegerField()),
            ],
        ),
    ]
