# Generated by Django 4.2.10 on 2025-01-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0031_gridtariff_matsertable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matsertable',
            name='RE_tariff',
        ),
        migrations.AlterField(
            model_name='gridtariff',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='matsertable',
            name='ISTS_charges',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='matsertable',
            name='state_charges',
            field=models.FloatField(),
        ),
    ]
