# Generated by Django 4.2.10 on 2025-01-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0032_remove_matsertable_re_tariff_alter_gridtariff_cost_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatserTable',
            new_name='MasterTable',
        ),
    ]
