# Generated by Django 4.2.10 on 2025-01-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0033_rename_matsertable_mastertable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardtermssheet',
            name='status',
        ),
        migrations.AddField(
            model_name='standardtermssheet',
            name='consumer_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Negotiated', 'Negotiated'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', help_text="Status from the consumer's perspective", max_length=100),
        ),
        migrations.AddField(
            model_name='standardtermssheet',
            name='generator_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Negotiated', 'Negotiated'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', help_text="Status from the generator's perspective", max_length=100),
        ),
    ]
