# Generated by Django 4.2.10 on 2025-01-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0034_remove_standardtermssheet_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardtermssheet',
            name='from_whom',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Negotiated', 'Negotiated'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=200, null=True),
        ),
    ]
