# Generated by Django 4.2.10 on 2025-01-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0035_standardtermssheet_from_whom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardtermssheet',
            name='from_whom',
            field=models.CharField(blank=True, choices=[('Consumer', 'Consumer'), ('Generator', 'Generator')], max_length=200, null=True),
        ),
    ]
