# Generated by Django 4.2.10 on 2025-01-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0036_alter_standardtermssheet_from_whom'),
    ]

    operations = [
        migrations.AddField(
            model_name='combination',
            name='terms_sheet_sent',
            field=models.BooleanField(default=False),
        ),
    ]
