# Generated by Django 4.2.10 on 2025-01-10 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('energy', '0037_combination_terms_sheet_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatoroffer',
            name='accepted_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_category': 'Generator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatoroffer',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
