# Generated by Django 4.2.10 on 2025-01-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0040_alter_monthlyconsumptiondata_monthly_bill_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScadaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='scada_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scada_file', to='energy.consumerrequirements')),
            ],
        ),
    ]
