# Generated by Django 4.2.10 on 2025-01-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0041_scadafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationwindow',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
