# Generated by Django 4.2.10 on 2025-01-17 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('energy', '0042_negotiationwindow_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('negotiation_window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='energy.negotiationwindow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
