# Generated by Django 4.2.10 on 2025-01-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0043_negotiationinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardtermssheet',
            name='offer_tariff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='combination',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
