# Generated by Django 4.2.10 on 2025-01-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0044_standardtermssheet_offer_tariff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combination',
            name='annual_demand_met',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
