# Generated by Django 4.2.10 on 2025-01-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0045_combination_annual_demand_met'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumerrequirements',
            old_name='site',
            new_name='consumption_unit',
        ),
    ]
