# Generated by Django 4.2.10 on 2025-01-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0046_rename_site_consumerrequirements_consumption_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlydemand',
            name='bulk_file',
        ),
        migrations.AddField(
            model_name='hourlydemand',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csv_files/'),
        ),
        migrations.AlterField(
            model_name='monthlyconsumptiondata',
            name='month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
