# Generated by Django 4.2.10 on 2025-01-21 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0047_remove_hourlydemand_bulk_file_hourlydemand_csv_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlydemand',
            name='requirement',
        ),
        migrations.AddField(
            model_name='hourlydemand',
            name='monthly_consumption',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='energy.monthlyconsumptiondata'),
            preserve_default=False,
        ),
    ]
