# Generated by Django 4.2.10 on 2025-01-21 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0048_remove_hourlydemand_requirement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlydemand',
            name='monthly_consumption',
        ),
        migrations.AddField(
            model_name='hourlydemand',
            name='requirement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='energy.consumerrequirements'),
            preserve_default=False,
        ),
    ]
