# Generated by Django 4.2.10 on 2025-01-23 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0049_remove_hourlydemand_monthly_consumption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='name',
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='subscription_type',
            field=models.CharField(choices=[('FREE', 'FREE'), ('ELITE', 'ELITE'), ('PRO', 'PRO')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='Invoice Number')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('company_address', models.TextField(verbose_name='Company Address')),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='GST Number')),
                ('gst_state', models.CharField(blank=True, max_length=50, null=True, verbose_name='GST State')),
                ('gst_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='GST Type')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Issue Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='performa_invoices/', verbose_name='Invoice File')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.subscriptiontype')),
            ],
            options={
                'verbose_name': 'Proforma Invoice',
                'verbose_name_plural': 'Proforma Invoices',
                'ordering': ['-issue_date'],
            },
        ),
    ]
