# Generated by Django 4.2.10 on 2025-01-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0050_remove_subscriptiontype_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='subscription_type',
            field=models.CharField(choices=[('FREE', 'FREE'), ('LITE', 'LITE'), ('PRO', 'PRO')], max_length=20),
        ),
    ]
