# Generated by Django 4.2.10 on 2025-01-23 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('energy', '0051_alter_subscriptiontype_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerrequirements',
            name='annual_electricity_consumption',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
