# Generated by Django 4.2.10 on 2025-01-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0052_consumerrequirements_annual_electricity_consumption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, verbose_name='Payment ID')),
                ('order_id', models.CharField(max_length=100, verbose_name='Order ID')),
                ('signature', models.CharField(max_length=100, verbose_name='signature')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
