# Generated by Django 4.2.10 on 2025-01-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0053_paymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
