# Generated by Django 4.2.10 on 2025-01-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0054_alter_paymenttransaction_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='RETariffMasterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('Health Care', 'Health Care')], max_length=255)),
                ('re_tariff', models.FloatField()),
            ],
        ),
    ]
