# Generated by Django 4.2.10 on 2025-01-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0056_alter_retariffmastertable_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='retariffmastertable',
            name='average_savings',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retariffmastertable',
            name='re_tariff',
            field=models.FloatField(default=None),
        ),
    ]
