# Generated by Django 4.2.10 on 2025-01-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0059_industry_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(choices=[('Retail', 'Retail'), ('Energy', 'Energy'), ('Materials', 'Materials'), ('Industrials', 'Industrials'), ('Consumer Discretionary', 'Consumer Discretionary'), ('Consumer Staples', 'Consumer Staples'), ('Health Care', 'Health Care'), ('Financials', 'Financials'), ('Information Technology', 'Information Technology'), ('Communication Services', 'Communication Services'), ('Utilities', 'Utilities'), ('Real Estate', 'Real Estate')], max_length=255),
        ),
    ]
