# Generated by Django 4.2.10 on 2025-01-25 05:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('energy', '0060_alter_industry_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProformaInvoice',
            new_name='PerformaInvoice',
        ),
    ]
