# Generated by Django 4.2.10 on 2025-01-28 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0061_rename_proformainvoice_performainvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performainvoice',
            name='invoice_file',
        ),
        migrations.AddField(
            model_name='monthlyconsumptiondata',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performainvoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 2, 7), verbose_name='Due Date'),
        ),
    ]
