# Generated by Django 4.2.10 on 2025-01-30 12:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('energy', '0062_remove_performainvoice_invoice_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performainvoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 2, 9), verbose_name='Due Date'),
        ),
    ]
