# Generated by Django 4.2.10 on 2025-01-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0063_paymenttransaction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performainvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Invoice Number'),
        ),
    ]
