# Generated by Django 4.2.10 on 2025-01-31 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0064_alter_performainvoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='combination',
            name='re_replacement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performainvoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 2, 10), verbose_name='Due Date'),
        ),
    ]
