# Generated by Django 4.2.10 on 2025-02-01 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0065_combination_re_replacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatoroffer',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='performainvoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 2, 11), verbose_name='Due Date'),
        ),
    ]
