# Generated by Django 4.2.10 on 2025-02-07 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0066_alter_generatoroffer_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performainvoice',
            name='gst_type',
        ),
        migrations.AddField(
            model_name='performainvoice',
            name='cgst',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='performainvoice',
            name='igst',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='performainvoice',
            name='sgst',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='performainvoice',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performainvoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 2, 17), verbose_name='Due Date'),
        ),
    ]
