# Generated by Django 4.2.10 on 2025-02-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0067_remove_performainvoice_gst_type_performainvoice_cgst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performainvoice',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Collapsed', 'Collapsed')], default='Pending', max_length=50),
        ),
    ]
