# Generated by Django 4.2.10 on 2025-02-07 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0068_performainvoice_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='invoice',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='energy.performainvoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performainvoice',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Collapsed', 'Collapsed')], default='Pending', max_length=50),
        ),
    ]
