# Generated by Django 4.2.10 on 2025-02-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0070_alter_performainvoice_due_date_alter_state_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffs',
            name='offer_tariff',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
