# Generated by Django 4.2.10 on 2025-02-10 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0071_alter_tariffs_offer_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationwindow',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='performainvoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 2, 20), verbose_name='Due Date'),
        ),
    ]
