# Generated by Django 4.2.10 on 2025-02-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0072_negotiationwindow_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negotiationwindow',
            name='status',
        ),
        migrations.AddField(
            model_name='tariffs',
            name='window_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Active', max_length=100),
        ),
    ]
