# Generated by Django 4.2.10 on 2025-02-14 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0073_remove_negotiationwindow_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardtermssheet',
            name='offer_tariff',
        ),
        migrations.AlterField(
            model_name='performainvoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 2, 24), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='standardtermssheet',
            name='consumer_status',
            field=models.CharField(choices=[('Counter Offer Sent', 'Counter Offer Sent'), ('Counter Offer Received', 'Counter Offer Received'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Counter Offer Sent', help_text="Status from the consumer's perspective", max_length=100),
        ),
        migrations.AlterField(
            model_name='standardtermssheet',
            name='generator_status',
            field=models.CharField(choices=[('Counter Offer Sent', 'Counter Offer Sent'), ('Counter Offer Received', 'Counter Offer Received'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Counter Offer Sent', help_text="Status from the generator's perspective", max_length=100),
        ),
    ]
