# Generated by Django 4.2.10 on 2025-02-17 04:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0074_remove_standardtermssheet_offer_tariff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(choices=[('Energy', 'Energy'), ('Materials', 'Materials'), ('Industrials', 'Industrials'), ('Consumer Discretionary', 'Consumer Discretionary'), ('Consumer Staples', 'Consumer Staples'), ('Health Care', 'Health Care'), ('Financials', 'Financials'), ('Information Technology', 'Information Technology'), ('Communication Services', 'Communication Services'), ('Utilities', 'Utilities'), ('Real Estate', 'Real Estate')], max_length=255),
        ),
        migrations.AlterField(
            model_name='performainvoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 2, 27), verbose_name='Due Date'),
        ),
        migrations.CreateModel(
            name='SubIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_industries', to='energy.industry')),
            ],
            options={
                'unique_together': {('industry', 'name')},
            },
        ),
    ]
