# Generated by Django 4.2.10 on 2025-02-20 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0077_notifications_is_read_alter_performainvoice_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performainvoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 3, 2), verbose_name='Due Date'),
        ),
    ]
