# Generated by Django 4.2.10 on 2025-02-22 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0079_standardtermssheet_consumer_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performainvoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 3, 4), verbose_name='Due Date'),
        ),
    ]
