# Generated by Django 4.2.10 on 2025-02-25 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0081_alter_performainvoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performainvoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 3, 7), verbose_name='Due Date'),
        ),
    ]
